server:
  port: 8082

spring:
  redis:
    #    host: 192.168.92.128
    host: 150.158.37.146
    port: 6379
    password:
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    password: oghxssklkzgmebce
    username: raycham@139.com
    port: 465
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
#    listener:
#      simple:
##        开启手动确认
#        acknowledge-mode: manual