server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.37.146:3306/yeb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 主动与数据库保持连接:远程访问的时候使用
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 50
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
#    host: 150.158.37.146
    host: 150.158.37.146
    port: 6379
    password: 123456
    database: 0
    timeout: 1000000ms
    lettuce:
      pool:
        # 最大活跃度
        max-active: 1024
        # 最大等待时间
        max-wait: 1000000ms
        # 最大连接
        max-idle: 200
        # 最小连接
        min-idle: 10
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
##    消息确认回调
#    publisher-confirm-type: correlated
##  消息失败回调
#    publisher-returns: true

mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名
  type-aliases-package: com.ray.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
# Mybatis SQL日志输出  打印方法接口所在的包
logging:
  level:
    com.ray.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加密使用的秘钥
  secret: yeb-secret
  # JWT超时时间（60*60*24）
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer
